/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e7c773a06e8563f322999e8
*
* You will get 10% discount for each one of your friends
* 
*/
// Dependencies
import React, { Component } from "react";
import { Fragment } from "react";
import { Route, Switch } from "react-router";
import { PrivateRoute } from "./security/PrivateRoute";

// Material UI
import Paper from "@material-ui/core/Paper";

/* START MY VIEWS IMPORT */

import DistributerEdit from "./pages/DistributerEdit";
import DistributerList from "./pages/DistributerList";
import EmployeesEdit from "./pages/EmployeesEdit";
import EmployeesList from "./pages/EmployeesList";
import FarmEdit from "./pages/FarmEdit";
import FarmList from "./pages/FarmList";
import PlantsEdit from "./pages/PlantsEdit";
import PlantsList from "./pages/PlantsList";
import ProductEdit from "./pages/ProductEdit";
import ProductList from "./pages/ProductList";

/* END MY VIEWS IMPORT */

// CUSTOM VIEWS
import Login from "./pages/Login";
import Home from "./pages/Home";
import Profile from "./pages/Profile";
import UserEdit from "./pages/UserEdit";
import UserList from "./pages/UserList";

class Routes extends Component {
  render() {
    return (
      <Switch>
        <Fragment>
          <Paper>
            <div className="main-cointainer">
              <Route exact path="/login" component={Login} />
              <PrivateRoute exact path="/" component={Home} />
              <PrivateRoute exact path="/profile" component={Profile} />
              <PrivateRoute exact path="/users/:id" component={UserEdit} roles={["ADMIN"]}/>
              <PrivateRoute exact path="/users" component={UserList} roles={["ADMIN"]}/>
              
              {/* CUSTOM VIEWS */}

              <PrivateRoute exact path="/home" component={Home} />

              {/* START MY VIEWS */}

              <PrivateRoute exact path="/distributers/:id" component={ DistributerEdit }  />
              <PrivateRoute exact path="/distributers" component={ DistributerList }  />
              <PrivateRoute exact path="/employeeses/:id" component={ EmployeesEdit }  />
              <PrivateRoute exact path="/employeeses" component={ EmployeesList }  />
              <PrivateRoute exact path="/farms/:id" component={ FarmEdit }  />
              <PrivateRoute exact path="/farms" component={ FarmList }  />
              <PrivateRoute exact path="/plantses/:id" component={ PlantsEdit }  />
              <PrivateRoute exact path="/plantses" component={ PlantsList }  />
              <PrivateRoute exact path="/products/:id" component={ ProductEdit }  />
              <PrivateRoute exact path="/products" component={ ProductList }  />

             {/* END MY VIEWS */}

            </div>
          </Paper>
        </Fragment>
      </Switch>
    );
  }
}

export default Routes;