/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e7c773a06e8563f322999e8
*
* You will get 10% discount for each one of your friends
* 
*/
// Dependencies
import React, { Component } from "react";
import { Link } from "react-router-dom";
import Utils from "../utils/utils";

// Redux
import PropTypes from "prop-types";
import { bindActionCreators } from "redux";
import { connect } from "react-redux";

// Material UI
import TextField from "@material-ui/core/TextField";
import Button from "@material-ui/core/Button";
import Select from "@material-ui/core/Select";
import MenuItem from "@material-ui/core/MenuItem";
import InputLabel from "@material-ui/core/InputLabel";
import FormControl from "@material-ui/core/FormControl";
import Chip from "@material-ui/core/Chip";
import Input from "@material-ui/core/Input";

// Custom Actions


// START IMPORT ACTIONS
import EmployeesActions from "../redux/actions/EmployeesActions";
import FarmActions from "../redux/actions/FarmActions";
import PlantsActions from "../redux/actions/PlantsActions";
import ProductActions from "../redux/actions/ProductActions";

// END IMPORT ACTIONS

/** APIs

* actionsEmployees.create
*	@description CRUD ACTION create
*
* actionsEmployees.update
*	@description CRUD ACTION update
*	@param ObjectId id - Id
*
* actionsEmployees.get
*	@description CRUD ACTION get
*	@param ObjectId id - Id resource
*
* actionsFarm.list
*	@description CRUD ACTION list
*
* actionsPlants.list
*	@description CRUD ACTION list
*
* actionsProduct.list
*	@description CRUD ACTION list
*

**/

class EmployeesEdit extends Component {
  // Init employees
  constructor(props) {
    super(props);
    this.state = {
      employees: {}
    };
  }

  // Load data on start
  componentDidMount() {
    if (this.props.match.params.id !== "new") {
      this.props.actionsEmployees.loadEmployees(this.props.match.params.id);
    }
    
    this.props.actionsFarm.loadFarmList();
    this.props.actionsPlants.loadPlantsList();
    this.props.actionsProduct.loadProductList();
  }

  // Insert props employees in state
  componentWillReceiveProps(props) {
    this.setState(...this.state, {
      employees: props.employees
    });
  }

  // Save data
  save(event) {
    event.preventDefault();
    if (this.state.employees._id) {
      this.props.actionsEmployees.saveEmployees(this.state.employees).then(data => {
        this.props.history.push("/employeeses/");
      });
    } else {
      this.props.actionsEmployees.createEmployees(this.state.employees).then(data => {
        this.props.history.push("/employeeses/");
      });
    }
  }

  // Show content
  render() {
    return (
      <div>
        <h1>Employees Edit</h1>
        <form className="myForm" onSubmit={this.save.bind(this)}>

          
          <TextField
            id="Address"
            label="Address"
            value={this.state.employees.Address || ""}
            onChange={Utils.handleChange.bind(this, "employees")}
            margin="normal"
            fullWidth
          />
          
          
          <TextField
            id="FirstName"
            label="FirstName"
            value={this.state.employees.FirstName || ""}
            onChange={Utils.handleChange.bind(this, "employees")}
            margin="normal"
            fullWidth
          />
          
          
          <TextField
            id="LastName"
            label="LastName"
            value={this.state.employees.LastName || ""}
            onChange={Utils.handleChange.bind(this, "employees")}
            margin="normal"
            fullWidth
            required
            {...(!this.state.employees.LastName && this.state.employees.LastName === ""
              ? { error: true }
              : {})}
          />
          
          
          <TextField
            id="Title"
            label="Title"
            value={this.state.employees.Title || ""}
            onChange={Utils.handleChange.bind(this, "employees")}
            margin="normal"
            fullWidth
            required
            {...(!this.state.employees.Title && this.state.employees.Title === ""
              ? { error: true }
              : {})}
          />
          
          {/* RELATIONS */}

          <h2 className="mb-20">Relations</h2>
          
          {/* Relation m:m _Farms with Farm */}
          
          <FormControl fullWidth className="mb-20">
            <InputLabel htmlFor="_Farms">_Farms</InputLabel>
            <Select
              multiple
              value={this.state.employees._Farms || []}
              onChange={Utils.handleChangeSelect.bind(this, "employees")}
              input={<Input id="_Farms" name="_Farms" />}
              renderValue={selected => (
                <div>
                  {selected.map(value => (
                    <Chip key={value} label={value} />
                  ))}
                </div>
              )}
            >
              {this.props.listFarm && this.props.listFarm.map(item => (
                <MenuItem
                  key={item._id}
                  value={item._id}
                  style={{
                    fontWeight:
                      this.state.employees._Farms &&
                      this.state.employees._Farms.indexOf(item._id) === -1
                        ? "regular"
                        : "bold"
                  }}
                >
                  {item._id}
                </MenuItem>
              ))}
            </Select>
          </FormControl>
          
          {/* Relation m:m _Plants with Plants */}
          
          <FormControl fullWidth className="mb-20">
            <InputLabel htmlFor="_Plants">_Plants</InputLabel>
            <Select
              multiple
              value={this.state.employees._Plants || []}
              onChange={Utils.handleChangeSelect.bind(this, "employees")}
              input={<Input id="_Plants" name="_Plants" />}
              renderValue={selected => (
                <div>
                  {selected.map(value => (
                    <Chip key={value} label={value} />
                  ))}
                </div>
              )}
            >
              {this.props.listPlants && this.props.listPlants.map(item => (
                <MenuItem
                  key={item._id}
                  value={item._id}
                  style={{
                    fontWeight:
                      this.state.employees._Plants &&
                      this.state.employees._Plants.indexOf(item._id) === -1
                        ? "regular"
                        : "bold"
                  }}
                >
                  {item._id}
                </MenuItem>
              ))}
            </Select>
          </FormControl>
          
          {/* Relation m:m _Product with Product */}
          
          <FormControl fullWidth className="mb-20">
            <InputLabel htmlFor="_Product">_Product</InputLabel>
            <Select
              multiple
              value={this.state.employees._Product || []}
              onChange={Utils.handleChangeSelect.bind(this, "employees")}
              input={<Input id="_Product" name="_Product" />}
              renderValue={selected => (
                <div>
                  {selected.map(value => (
                    <Chip key={value} label={value} />
                  ))}
                </div>
              )}
            >
              {this.props.listProduct && this.props.listProduct.map(item => (
                <MenuItem
                  key={item._id}
                  value={item._id}
                  style={{
                    fontWeight:
                      this.state.employees._Product &&
                      this.state.employees._Product.indexOf(item._id) === -1
                        ? "regular"
                        : "bold"
                  }}
                >
                  {item._id}
                </MenuItem>
              ))}
            </Select>
          </FormControl>
          
          {/* Footer */}
          <div className="footer-card">
            <Link to="/employeeses/">Back to list</Link>

            <Button type="submit" variant="contained" color="primary">
              Save
            </Button>
          </div>
        </form>
      </div>
    );
  }
}

// Store actions
const mapDispatchToProps = function(dispatch) {
  return { 
    actionsEmployees: bindActionCreators(EmployeesActions, dispatch),
    actionsFarm: bindActionCreators(FarmActions, dispatch),
    actionsPlants: bindActionCreators(PlantsActions, dispatch),
    actionsProduct: bindActionCreators(ProductActions, dispatch),
  };
};

// Validate types
EmployeesEdit.propTypes = { 
  actionsEmployees: PropTypes.object.isRequired,
  actionsFarm: PropTypes.object.isRequired,
  actionsPlants: PropTypes.object.isRequired,
  actionsProduct: PropTypes.object.isRequired,
};

// Get props from state
function mapStateToProps(state, ownProps) {
  return {
    employees: state.EmployeesEditReducer.employees,
    listFarm: state.EmployeesEditReducer.listFarm,
    listPlants: state.EmployeesEditReducer.listPlants,
    listProduct: state.EmployeesEditReducer.listProduct
  };
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(EmployeesEdit);
