/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e7c773a06e8563f322999e8
*
* You will get 10% discount for each one of your friends
* 
*/
// Dependencies
import React, { Component } from "react";
import { Link } from "react-router-dom";
import Utils from "../utils/utils";

// Redux
import PropTypes from "prop-types";
import { bindActionCreators } from "redux";
import { connect } from "react-redux";

// Material UI
import TextField from "@material-ui/core/TextField";
import Button from "@material-ui/core/Button";
import Select from "@material-ui/core/Select";
import MenuItem from "@material-ui/core/MenuItem";
import InputLabel from "@material-ui/core/InputLabel";
import FormControl from "@material-ui/core/FormControl";

// Custom Actions


// START IMPORT ACTIONS
import FarmActions from "../redux/actions/FarmActions";
import DistributerActions from "../redux/actions/DistributerActions";
import PlantsActions from "../redux/actions/PlantsActions";
import EmployeesActions from "../redux/actions/EmployeesActions";

// END IMPORT ACTIONS

/** APIs

* actionsFarm.create
*	@description CRUD ACTION create
*
* actionsFarm.update
*	@description CRUD ACTION update
*	@param ObjectId id - Id
*
* actionsFarm.get
*	@description CRUD ACTION get
*	@param ObjectId id - Id resource
*
* actionsDistributer.list
*	@description CRUD ACTION list
*
* actionsPlants.list
*	@description CRUD ACTION list
*
* actionsPlants.findBy_Farms
*	@description CRUD ACTION findBy_Farms
*	@param Objectid key - Id of model to search for
*
* actionsDistributer.findBy_Farms
*	@description CRUD ACTION findBy_Farms
*	@param Objectid key - Id of model to search for
*
* actionsEmployees.findBy_Farms
*	@description CRUD ACTION findBy_Farms
*	@param Objectid key - Id of model to search for
*

**/

class FarmEdit extends Component {
  // Init farm
  constructor(props) {
    super(props);
    this.state = {
      farm: {}
    };
  }

  // Load data on start
  componentDidMount() {
    if (this.props.match.params.id !== "new") {
      this.props.actionsFarm.loadFarm(this.props.match.params.id);
      this.props.actionsDistributer.findBy_Farms(this.props.match.params.id);
      this.props.actionsEmployees.findBy_Farms(this.props.match.params.id);
      this.props.actionsPlants.findBy_Farms(this.props.match.params.id);
    }
    
    this.props.actionsDistributer.loadDistributerList();
    this.props.actionsPlants.loadPlantsList();
  }

  // Insert props farm in state
  componentWillReceiveProps(props) {
    this.setState(...this.state, {
      farm: props.farm
    });
  }

  // Save data
  save(event) {
    event.preventDefault();
    if (this.state.farm._id) {
      this.props.actionsFarm.saveFarm(this.state.farm).then(data => {
        this.props.history.push("/farms/");
      });
    } else {
      this.props.actionsFarm.createFarm(this.state.farm).then(data => {
        this.props.history.push("/farms/");
      });
    }
  }

  // Show content
  render() {
    return (
      <div>
        <h1>Farm Edit</h1>
        <form className="myForm" onSubmit={this.save.bind(this)}>

          
          <TextField
            id="Address"
            label="Address"
            value={this.state.farm.Address || ""}
            onChange={Utils.handleChange.bind(this, "farm")}
            margin="normal"
            fullWidth
          />
          
          
          <TextField
            id="Name"
            label="Name"
            value={this.state.farm.Name || ""}
            onChange={Utils.handleChange.bind(this, "farm")}
            margin="normal"
            fullWidth
            required
            {...(!this.state.farm.Name && this.state.farm.Name === ""
              ? { error: true }
              : {})}
          />
          
          
          <TextField
            id="Status"
            label="Status"
            value={this.state.farm.Status || ""}
            onChange={Utils.handleChange.bind(this, "farm")}
            margin="normal"
            fullWidth
          />
          
          {/* RELATIONS */}

          <h2 className="mb-20">Relations</h2>
          
          {/* Relation 1:m _Distributer with Distributer */}
          
          <FormControl fullWidth className="mb-20">
            <InputLabel shrink htmlFor="_Distributer">
              _Distributer
            </InputLabel>
            <Select
              value={this.state.farm._Distributer || ""}
              onChange={Utils.handleChangeSelect.bind(this, "farm")}
              inputProps={{
                id: "_Distributer",
                name: "_Distributer"
              }}
              fullWidth
            >
              <MenuItem value="">
                <em>None</em>
              </MenuItem>
              {this.props.listDistributer && this.props.listDistributer.map(row => (
                <MenuItem value={row._id} key={row._id}>
                  {row._id}
                </MenuItem>
              ))}
            </Select>
          </FormControl>
          
          
          {/* Relation 1:m _Plants with Plants */}
          
          <FormControl fullWidth className="mb-20">
            <InputLabel shrink htmlFor="_Plants">
              _Plants
            </InputLabel>
            <Select
              value={this.state.farm._Plants || ""}
              onChange={Utils.handleChangeSelect.bind(this, "farm")}
              inputProps={{
                id: "_Plants",
                name: "_Plants"
              }}
              fullWidth
            >
              <MenuItem value="">
                <em>None</em>
              </MenuItem>
              {this.props.listPlants && this.props.listPlants.map(row => (
                <MenuItem value={row._id} key={row._id}>
                  {row._id}
                </MenuItem>
              ))}
            </Select>
          </FormControl>
          
          
          {/* EXTERNAL RELATIONS */}
          
          {/* External relation with Distributer */}
          
          <h3>Distributer</h3>
          {(!this.props.listDistributer || this.props.listDistributer.length === 0) && 
            <div>No Distributer associated</div>
          }
          {this.props.listDistributer &&
            this.props.listDistributer.map((item, i) => {
              return (
                <Link to={"/distributers/" + item._id} key={item._id}>
                  {item._id}
                </Link>
              );
            })}

          
          {/* External relation with Employees */}
          
          <h3>Employees</h3>
          {(!this.props.listEmployees || this.props.listEmployees.length === 0) && 
            <div>No Employees associated</div>
          }
          {this.props.listEmployees &&
            this.props.listEmployees.map((item, i) => {
              return (
                <Link to={"/employeess/" + item._id} key={item._id}>
                  {item._id}
                </Link>
              );
            })}

          
          {/* External relation with Plants */}
          
          <h3>Plants</h3>
          {(!this.props.listPlants || this.props.listPlants.length === 0) && 
            <div>No Plants associated</div>
          }
          {this.props.listPlants &&
            this.props.listPlants.map((item, i) => {
              return (
                <Link to={"/plantss/" + item._id} key={item._id}>
                  {item._id}
                </Link>
              );
            })}

          
          {/* Footer */}
          <div className="footer-card">
            <Link to="/farms/">Back to list</Link>

            <Button type="submit" variant="contained" color="primary">
              Save
            </Button>
          </div>
        </form>
      </div>
    );
  }
}

// Store actions
const mapDispatchToProps = function(dispatch) {
  return { 
    actionsFarm: bindActionCreators(FarmActions, dispatch),
    actionsDistributer: bindActionCreators(DistributerActions, dispatch),
    actionsPlants: bindActionCreators(PlantsActions, dispatch),
    actionsEmployees: bindActionCreators(EmployeesActions, dispatch),
  };
};

// Validate types
FarmEdit.propTypes = { 
  actionsFarm: PropTypes.object.isRequired,
  actionsDistributer: PropTypes.object.isRequired,
  actionsPlants: PropTypes.object.isRequired,
  actionsEmployees: PropTypes.object.isRequired,
};

// Get props from state
function mapStateToProps(state, ownProps) {
  return {
    farm: state.FarmEditReducer.farm,
    listDistributer: state.FarmEditReducer.listDistributer,
    listPlants: state.FarmEditReducer.listPlants,
    listDistributer: state.FarmEditReducer.listDistributer,
    listEmployees: state.FarmEditReducer.listEmployees,
    listPlants: state.FarmEditReducer.listPlants
  };
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(FarmEdit);
