/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e7c773a06e8563f322999e8
*
* You will get 10% discount for each one of your friends
* 
*/
// Dependencies
import React, { Component } from "react";
import { Link } from "react-router-dom";
import Utils from "../utils/utils";

// Redux
import PropTypes from "prop-types";
import { bindActionCreators } from "redux";
import { connect } from "react-redux";

// Material UI
import TextField from "@material-ui/core/TextField";
import Button from "@material-ui/core/Button";
import { DateTimePicker } from "material-ui-pickers";
import Select from "@material-ui/core/Select";
import MenuItem from "@material-ui/core/MenuItem";
import InputLabel from "@material-ui/core/InputLabel";
import FormControl from "@material-ui/core/FormControl";

// Custom Actions


// START IMPORT ACTIONS
import ProductActions from "../redux/actions/ProductActions";
import PlantsActions from "../redux/actions/PlantsActions";
import DistributerActions from "../redux/actions/DistributerActions";
import EmployeesActions from "../redux/actions/EmployeesActions";

// END IMPORT ACTIONS

/** APIs

* actionsProduct.create
*	@description CRUD ACTION create
*
* actionsProduct.update
*	@description CRUD ACTION update
*	@param ObjectId id - Id
*
* actionsProduct.get
*	@description CRUD ACTION get
*	@param ObjectId id - Id resource
*
* actionsPlants.findBy_Products
*	@description CRUD ACTION findBy_Products
*	@param Objectid key - Id of model to search for
*
* actionsPlants.list
*	@description CRUD ACTION list
*
* actionsDistributer.findBy_Product
*	@description CRUD ACTION findBy_Product
*	@param Objectid key - Id of model to search for
*
* actionsEmployees.findBy_Product
*	@description CRUD ACTION findBy_Product
*	@param Objectid key - Id of model to search for
*

**/

class ProductEdit extends Component {
  // Init product
  constructor(props) {
    super(props);
    this.state = {
      product: {}
    };
  }

  // Load data on start
  componentDidMount() {
    if (this.props.match.params.id !== "new") {
      this.props.actionsProduct.loadProduct(this.props.match.params.id);
      this.props.actionsDistributer.findBy_Product(this.props.match.params.id);
      this.props.actionsEmployees.findBy_Product(this.props.match.params.id);
      this.props.actionsPlants.findBy_Products(this.props.match.params.id);
    }
    
    this.props.actionsPlants.loadPlantsList();
  }

  // Insert props product in state
  componentWillReceiveProps(props) {
    this.setState(...this.state, {
      product: props.product
    });
  }

  // Save data
  save(event) {
    event.preventDefault();
    if (this.state.product._id) {
      this.props.actionsProduct.saveProduct(this.state.product).then(data => {
        this.props.history.push("/products/");
      });
    } else {
      this.props.actionsProduct.createProduct(this.state.product).then(data => {
        this.props.history.push("/products/");
      });
    }
  }

  // Show content
  render() {
    return (
      <div>
        <h1>Product Edit</h1>
        <form className="myForm" onSubmit={this.save.bind(this)}>

          
          <TextField
            id="BarCode"
            label="BarCode"
            value={this.state.product.BarCode || ""}
            onChange={Utils.handleChange.bind(this, "product")}
            margin="normal"
            fullWidth
            required
            {...(!this.state.product.BarCode && this.state.product.BarCode === ""
              ? { error: true }
              : {})}
          />
          
          <DateTimePicker
            id="DateCreated"
            label="DateCreated"
            className="mt-20 mb-20"
            ampm={false}
            value={
              this.state.product.DateCreated
                ? new Date(this.state.product.DateCreated)
                : null
            }
            onChange={Utils.handleChangeDate.bind(this, "product", "DateCreated")}
            fullWidth
            autoOk
            disableFuture
            required
            {...(!this.state.product.DateCreated && this.state.product.DateCreated === ""
              ? { error: true }
              : {})}
          />
          
          
          <TextField
            id="PlantBarCode"
            label="PlantBarCode"
            value={this.state.product.PlantBarCode || ""}
            onChange={Utils.handleChange.bind(this, "product")}
            margin="normal"
            fullWidth
            required
            {...(!this.state.product.PlantBarCode && this.state.product.PlantBarCode === ""
              ? { error: true }
              : {})}
          />
          
          
          <TextField
            id="ProductType"
            label="ProductType"
            value={this.state.product.ProductType || ""}
            onChange={Utils.handleChange.bind(this, "product")}
            margin="normal"
            fullWidth
          />
          
          {/* RELATIONS */}

          <h2 className="mb-20">Relations</h2>
          
          {/* Relation 1:m _Plants with Plants */}
          
          <FormControl fullWidth className="mb-20">
            <InputLabel shrink htmlFor="_Plants">
              _Plants
            </InputLabel>
            <Select
              value={this.state.product._Plants || ""}
              onChange={Utils.handleChangeSelect.bind(this, "product")}
              inputProps={{
                id: "_Plants",
                name: "_Plants"
              }}
              fullWidth
            >
              <MenuItem value="">
                <em>None</em>
              </MenuItem>
              {this.props.listPlants && this.props.listPlants.map(row => (
                <MenuItem value={row._id} key={row._id}>
                  {row._id}
                </MenuItem>
              ))}
            </Select>
          </FormControl>
          
          
          {/* EXTERNAL RELATIONS */}
          
          {/* External relation with Distributer */}
          
          <h3>Distributer</h3>
          {(!this.props.listDistributer || this.props.listDistributer.length === 0) && 
            <div>No Distributer associated</div>
          }
          {this.props.listDistributer &&
            this.props.listDistributer.map((item, i) => {
              return (
                <Link to={"/distributers/" + item._id} key={item._id}>
                  {item._id}
                </Link>
              );
            })}

          
          {/* External relation with Employees */}
          
          <h3>Employees</h3>
          {(!this.props.listEmployees || this.props.listEmployees.length === 0) && 
            <div>No Employees associated</div>
          }
          {this.props.listEmployees &&
            this.props.listEmployees.map((item, i) => {
              return (
                <Link to={"/employeess/" + item._id} key={item._id}>
                  {item._id}
                </Link>
              );
            })}

          
          {/* External relation with Plants */}
          
          <h3>Plants</h3>
          {(!this.props.listPlants || this.props.listPlants.length === 0) && 
            <div>No Plants associated</div>
          }
          {this.props.listPlants &&
            this.props.listPlants.map((item, i) => {
              return (
                <Link to={"/plantss/" + item._id} key={item._id}>
                  {item._id}
                </Link>
              );
            })}

          
          {/* Footer */}
          <div className="footer-card">
            <Link to="/products/">Back to list</Link>

            <Button type="submit" variant="contained" color="primary">
              Save
            </Button>
          </div>
        </form>
      </div>
    );
  }
}

// Store actions
const mapDispatchToProps = function(dispatch) {
  return { 
    actionsProduct: bindActionCreators(ProductActions, dispatch),
    actionsPlants: bindActionCreators(PlantsActions, dispatch),
    actionsDistributer: bindActionCreators(DistributerActions, dispatch),
    actionsEmployees: bindActionCreators(EmployeesActions, dispatch),
  };
};

// Validate types
ProductEdit.propTypes = { 
  actionsProduct: PropTypes.object.isRequired,
  actionsPlants: PropTypes.object.isRequired,
  actionsDistributer: PropTypes.object.isRequired,
  actionsEmployees: PropTypes.object.isRequired,
};

// Get props from state
function mapStateToProps(state, ownProps) {
  return {
    product: state.ProductEditReducer.product,
    listPlants: state.ProductEditReducer.listPlants,
    listDistributer: state.ProductEditReducer.listDistributer,
    listEmployees: state.ProductEditReducer.listEmployees,
    listPlants: state.ProductEditReducer.listPlants
  };
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(ProductEdit);
