/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e7c773a06e8563f322999e8
*
* You will get 10% discount for each one of your friends
* 
*/

// INSERT HERE YOUR CUSTOM CONSTANTS




// START CRUD CONSTANTS

// DISTRIBUTER
export const CREATE_DISTRIBUTER_SUCCESS = "CREATE_DISTRIBUTER_SUCCESS";
export const DELETE_DISTRIBUTER_SUCCESS = "DELETE_DISTRIBUTER_SUCCESS";
export const FINDBY_FARMS_DISTRIBUTER_SUCCESS = "FINDBY_FARMS_DISTRIBUTER_SUCCESS";
export const FINDBY_PRODUCT_DISTRIBUTER_SUCCESS = "FINDBY_PRODUCT_DISTRIBUTER_SUCCESS";
export const GET_DISTRIBUTER_SUCCESS = "GET_DISTRIBUTER_SUCCESS";
export const LIST_DISTRIBUTER_SUCCESS = "LIST_DISTRIBUTER_SUCCESS";
export const UPDATE_DISTRIBUTER_SUCCESS = "UPDATE_DISTRIBUTER_SUCCESS";

// EMPLOYEES
export const CREATE_EMPLOYEES_SUCCESS = "CREATE_EMPLOYEES_SUCCESS";
export const DELETE_EMPLOYEES_SUCCESS = "DELETE_EMPLOYEES_SUCCESS";
export const FINDBY_FARMS_EMPLOYEES_SUCCESS = "FINDBY_FARMS_EMPLOYEES_SUCCESS";
export const FINDBY_PLANTS_EMPLOYEES_SUCCESS = "FINDBY_PLANTS_EMPLOYEES_SUCCESS";
export const FINDBY_PRODUCT_EMPLOYEES_SUCCESS = "FINDBY_PRODUCT_EMPLOYEES_SUCCESS";
export const GET_EMPLOYEES_SUCCESS = "GET_EMPLOYEES_SUCCESS";
export const LIST_EMPLOYEES_SUCCESS = "LIST_EMPLOYEES_SUCCESS";
export const UPDATE_EMPLOYEES_SUCCESS = "UPDATE_EMPLOYEES_SUCCESS";

// FARM
export const CREATE_FARM_SUCCESS = "CREATE_FARM_SUCCESS";
export const DELETE_FARM_SUCCESS = "DELETE_FARM_SUCCESS";
export const FINDBY_DISTRIBUTER_FARM_SUCCESS = "FINDBY_DISTRIBUTER_FARM_SUCCESS";
export const FINDBY_PLANTS_FARM_SUCCESS = "FINDBY_PLANTS_FARM_SUCCESS";
export const GET_FARM_SUCCESS = "GET_FARM_SUCCESS";
export const LIST_FARM_SUCCESS = "LIST_FARM_SUCCESS";
export const UPDATE_FARM_SUCCESS = "UPDATE_FARM_SUCCESS";

// PLANTS
export const CREATE_PLANTS_SUCCESS = "CREATE_PLANTS_SUCCESS";
export const DELETE_PLANTS_SUCCESS = "DELETE_PLANTS_SUCCESS";
export const FINDBY_FARMS_PLANTS_SUCCESS = "FINDBY_FARMS_PLANTS_SUCCESS";
export const FINDBY_PRODUCTS_PLANTS_SUCCESS = "FINDBY_PRODUCTS_PLANTS_SUCCESS";
export const GET_PLANTS_SUCCESS = "GET_PLANTS_SUCCESS";
export const LIST_PLANTS_SUCCESS = "LIST_PLANTS_SUCCESS";
export const UPDATE_PLANTS_SUCCESS = "UPDATE_PLANTS_SUCCESS";

// PRODUCT
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";
export const FINDBY_PLANTS_PRODUCT_SUCCESS = "FINDBY_PLANTS_PRODUCT_SUCCESS";
export const GET_PRODUCT_SUCCESS = "GET_PRODUCT_SUCCESS";
export const LIST_PRODUCT_SUCCESS = "LIST_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";

// USER
export const CHANGEPASSWORD_USER_SUCCESS = "CHANGEPASSWORD_USER_SUCCESS";
export const CREATE_USER_SUCCESS = "CREATE_USER_SUCCESS";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const LIST_USER_SUCCESS = "LIST_USER_SUCCESS";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

// END CRUD CONSTANTS

// USER
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const CHANGE_PASSWORD_SUCCESS = "CHANGE_PASSWORD_SUCCESS";
export const CHANGE_PASSWORD_ADMIN_SUCCESS = "CHANGE_PASSWORD_ADMIN_SUCCESS";
